/*
 * manifest.js — THE SITE REGISTRY (single source of truth).
 *
 * Every page the site has or plans to have lives here. The build reads this to
 * render pages, auto-generate sitemap.xml + llms.txt, wire navigation and
 * breadcrumbs, and report coverage. Add a page = add a row here. Holds the full
 * 1,000–1,500 page vision as data — generated from the audited content plan,
 * then maintained by hand (flip status 'planned' → 'built' as pages ship).
 *
 * Generated by scripts/seed-manifest.js · 237 pages across 11 pillars.
 */
module.exports = {
  site: 'https://floridarealtorcareers.com',
  brand: 'Florida Realtor Careers — Adams, Cameron & Co., Realtors',
  pillars: [
  {
    "id": "master",
    "title": "Become a Real Estate Agent in Florida",
    "hub": "become-a-real-estate-agent-in-florida",
    "kicker": "The master guide"
  },
  {
    "id": "local",
    "title": "Real Estate Careers by City",
    "hub": "real-estate-careers-volusia-flagler",
    "universe": "Local Area Pages",
    "format": "Collection",
    "planned": 56
  },
  {
    "id": "license",
    "title": "Get Your Florida License",
    "hub": "florida-real-estate-license",
    "universe": "Getting Your Florida Real Estate License",
    "format": "Article",
    "planned": 20
  },
  {
    "id": "decide",
    "title": "Decide If It’s Right for You",
    "hub": "is-real-estate-career-right-for-you",
    "universe": "Is a Real Estate Career Right for You?",
    "format": "Article",
    "planned": 20
  },
  {
    "id": "brokerage",
    "title": "Choose the Right Brokerage",
    "hub": "choosing-a-real-estate-brokerage",
    "universe": "Choosing the Right Brokerage in Volusia & Flagler County",
    "format": "Comparison",
    "planned": 20
  },
  {
    "id": "business",
    "title": "Build Your Business",
    "hub": "building-your-real-estate-business",
    "universe": "Building Your Real Estate Business in Volusia & Flagler County",
    "format": "Article",
    "planned": 20
  },
  {
    "id": "market",
    "title": "Know the Local Market",
    "hub": "volusia-flagler-real-estate-market",
    "universe": "Understanding the Volusia & Flagler County Real Estate Market",
    "format": "Article",
    "planned": 20
  },
  {
    "id": "training",
    "title": "Training, Tools & Resources",
    "hub": "new-agent-training",
    "universe": "New Agent Training, Tools & Resources",
    "format": "FAQ",
    "planned": 22
  },
  {
    "id": "advancement",
    "title": "Advance & Upgrade Your License",
    "hub": "real-estate-license-upgrades",
    "universe": "Agent Career Advancement & Licensing Upgrades",
    "format": "Article",
    "planned": 17
  },
  {
    "id": "income",
    "title": "Income, Costs & Tools",
    "hub": "real-estate-agent-income-florida",
    "universe": "Costs, Income & Financial Reality of Real Estate Careers",
    "format": "Tool",
    "planned": 14
  },
  {
    "id": "stories",
    "title": "Stories, Culture & Community",
    "hub": "real-estate-agent-stories-daytona",
    "universe": "Local Career Stories, Culture & Community",
    "format": "Collection",
    "planned": 15
  }
],
  pages: [
  {
    "slug": "become-a-real-estate-agent-in-florida",
    "type": "hub",
    "pillar": "master",
    "title": "How to Become a Real Estate Agent in Florida",
    "status": "built",
    "spec": "content/become-a-real-estate-agent-in-florida.json"
  },
  {
    "slug": "real-estate-careers-volusia-flagler",
    "type": "hub",
    "pillar": "local",
    "title": "Real Estate Careers by City",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-daytona-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in Daytona Beach, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-daytona-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in Daytona Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-daytona-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in Daytona Beach, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-daytona-beach-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the Daytona Beach Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-daytona-beach-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in Daytona Beach, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-daytona-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in Daytona Beach, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-daytona-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in Daytona Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-daytona-beach-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for Daytona Beach, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-ormond-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in Ormond Beach, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-ormond-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in Ormond Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-ormond-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in Ormond Beach, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-ormond-beach-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the Ormond Beach Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-ormond-beach-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in Ormond Beach, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-ormond-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in Ormond Beach, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-ormond-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in Ormond Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-ormond-beach-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for Ormond Beach, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-palm-coast-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in Palm Coast, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-palm-coast-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in Palm Coast, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-palm-coast-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in Palm Coast, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-palm-coast-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the Palm Coast Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-palm-coast-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in Palm Coast, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-palm-coast-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in Palm Coast, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-palm-coast-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in Palm Coast, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-palm-coast-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for Palm Coast, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-deltona-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in Deltona, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-deltona-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in Deltona, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-deltona-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in Deltona, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-deltona-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the Deltona Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-deltona-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in Deltona, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-deltona-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in Deltona, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-deltona-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in Deltona, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-deltona-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for Deltona, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-deland-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in DeLand, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-deland-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in DeLand, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-deland-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in DeLand, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-deland-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the DeLand Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-deland-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in DeLand, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-deland-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in DeLand, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-deland-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in DeLand, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-deland-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for DeLand, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-new-smyrna-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in New Smyrna Beach, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-new-smyrna-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in New Smyrna Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-new-smyrna-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in New Smyrna Beach, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-new-smyrna-beach-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the New Smyrna Beach Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-new-smyrna-beach-florida-what-you-need-to-kn",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in New Smyrna Beach, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-new-smyrna-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in New Smyrna Beach, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-new-smyrna-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in New Smyrna Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-new-smyrna-beach-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for New Smyrna Beach, FL Residents",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-agent-in-flagler-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How to Become a Real Estate Agent in Flagler Beach, FL",
    "status": "planned"
  },
  {
    "slug": "best-real-estate-brokerages-to-join-in-flagler-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Best Real Estate Brokerages to Join in Flagler Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-career-opportunities-in-flagler-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate Agent Career Opportunities in Flagler Beach, FL",
    "status": "planned"
  },
  {
    "slug": "what-new-real-estate-agents-should-know-about-the-flagler-beach-market",
    "type": "article",
    "pillar": "local",
    "title": "What New Real Estate Agents Should Know About the Flagler Beach Market",
    "status": "planned"
  },
  {
    "slug": "switching-real-estate-brokerages-in-flagler-beach-florida-what-you-need-to-know",
    "type": "article",
    "pillar": "local",
    "title": "Switching Real Estate Brokerages in Flagler Beach, Florida: What You Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-earn-in-flagler-beach-fl",
    "type": "article",
    "pillar": "local",
    "title": "How Much Do Real Estate Agents Earn in Flagler Beach, FL?",
    "status": "planned"
  },
  {
    "slug": "top-questions-about-starting-a-real-estate-career-in-flagler-beach-florida",
    "type": "article",
    "pillar": "local",
    "title": "Top Questions About Starting a Real Estate Career in Flagler Beach, Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-requirements-for-flagler-beach-fl-residents",
    "type": "article",
    "pillar": "local",
    "title": "Real Estate License Requirements for Flagler Beach, FL Residents",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license",
    "type": "hub",
    "pillar": "license",
    "title": "Get Your Florida License",
    "status": "planned"
  },
  {
    "slug": "how-to-get-your-florida-real-estate-license-step-by-step-guide",
    "type": "article",
    "pillar": "license",
    "title": "How to Get Your Florida Real Estate License: Step-by-Step Guide",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license-requirements-in-2024",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate License Requirements in 2024",
    "status": "planned"
  },
  {
    "slug": "how-long-does-it-take-to-get-a-florida-real-estate-license",
    "type": "article",
    "pillar": "license",
    "title": "How Long Does It Take to Get a Florida Real Estate License?",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-pre-license-course-what-to-expect",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate Pre-License Course: What to Expect",
    "status": "planned"
  },
  {
    "slug": "how-much-does-it-cost-to-get-a-florida-real-estate-license",
    "type": "article",
    "pillar": "license",
    "title": "How Much Does It Cost to Get a Florida Real Estate License?",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-exam-what-you-need-to-know-before-test-day",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate Exam: What You Need to Know Before Test Day",
    "status": "planned"
  },
  {
    "slug": "passing-the-florida-real-estate-state-exam-on-your-first-try",
    "type": "article",
    "pillar": "license",
    "title": "Passing the Florida Real Estate State Exam on Your First Try",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license-exam-pass-rates-and-what-they-mean-for-you",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate License Exam Pass Rates and What They Mean for You",
    "status": "planned"
  },
  {
    "slug": "frec-approved-real-estate-schools-near-daytona-beach",
    "type": "article",
    "pillar": "license",
    "title": "FREC-Approved Real Estate Schools Near Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "online-vs-in-person-real-estate-pre-license-courses-in-florida",
    "type": "article",
    "pillar": "license",
    "title": "Online vs. In-Person Real Estate Pre-License Courses in Florida",
    "status": "planned"
  },
  {
    "slug": "the-63-hour-florida-pre-license-course-topics-tips-and-timelines",
    "type": "article",
    "pillar": "license",
    "title": "The 63-Hour Florida Pre-License Course: Topics, Tips, and Timelines",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-background-check-what-disqualifies-you",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate Background Check: What Disqualifies You?",
    "status": "planned"
  },
  {
    "slug": "how-to-apply-for-your-florida-real-estate-license-after-passing-the-exam",
    "type": "article",
    "pillar": "license",
    "title": "How to Apply for Your Florida Real Estate License After Passing the Exam",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license-reciprocity-moving-to-volusia-county-from-another-st",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate License Reciprocity: Moving to Volusia County from Another State",
    "status": "planned"
  },
  {
    "slug": "what-is-the-pearson-vue-real-estate-exam-and-where-do-you-take-it-near-daytona-b",
    "type": "article",
    "pillar": "license",
    "title": "What Is the Pearson VUE Real Estate Exam and Where Do You Take It Near Daytona Beach?",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-post-license-requirements-what-new-agents-must-complete",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate Post-License Requirements: What New Agents Must Complete",
    "status": "planned"
  },
  {
    "slug": "how-to-study-for-the-florida-real-estate-exam-while-working-full-time",
    "type": "article",
    "pillar": "license",
    "title": "How to Study for the Florida Real Estate Exam While Working Full-Time",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license-renewal-deadlines-ce-hours-and-how-it-works",
    "type": "article",
    "pillar": "license",
    "title": "Florida Real Estate License Renewal: Deadlines, CE Hours, and How It Works",
    "status": "planned"
  },
  {
    "slug": "can-you-get-a-florida-real-estate-license-with-a-felony",
    "type": "article",
    "pillar": "license",
    "title": "Can You Get a Florida Real Estate License with a Felony?",
    "status": "planned"
  },
  {
    "slug": "what-happens-after-you-pass-the-florida-real-estate-exam",
    "type": "article",
    "pillar": "license",
    "title": "What Happens After You Pass the Florida Real Estate Exam?",
    "status": "planned"
  },
  {
    "slug": "is-real-estate-career-right-for-you",
    "type": "hub",
    "pillar": "decide",
    "title": "Decide If It’s Right for You",
    "status": "planned"
  },
  {
    "slug": "is-real-estate-a-good-career-in-daytona-beach-in-2024",
    "type": "article",
    "pillar": "decide",
    "title": "Is Real Estate a Good Career in Daytona Beach in 2024?",
    "status": "planned"
  },
  {
    "slug": "what-does-a-day-in-the-life-of-a-real-estate-agent-in-volusia-county-actually-lo",
    "type": "article",
    "pillar": "decide",
    "title": "What Does a Day in the Life of a Real Estate Agent in Volusia County Actually Look Like?",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-vs-real-estate-broker-in-florida-whats-the-difference",
    "type": "article",
    "pillar": "decide",
    "title": "Real Estate Agent vs. Real Estate Broker in Florida: What's the Difference?",
    "status": "planned"
  },
  {
    "slug": "how-much-do-real-estate-agents-make-in-volusia-county-florida",
    "type": "article",
    "pillar": "decide",
    "title": "How Much Do Real Estate Agents Make in Volusia County, Florida?",
    "status": "planned"
  },
  {
    "slug": "part-time-vs-full-time-real-estate-agent-in-florida-pros-and-cons",
    "type": "article",
    "pillar": "decide",
    "title": "Part-Time vs. Full-Time Real Estate Agent in Florida: Pros and Cons",
    "status": "planned"
  },
  {
    "slug": "can-you-make-a-living-as-a-real-estate-agent-in-a-smaller-market-like-flagler-co",
    "type": "article",
    "pillar": "decide",
    "title": "Can You Make a Living as a Real Estate Agent in a Smaller Market Like Flagler County?",
    "status": "planned"
  },
  {
    "slug": "what-skills-do-you-actually-need-to-succeed-as-a-real-estate-agent",
    "type": "article",
    "pillar": "decide",
    "title": "What Skills Do You Actually Need to Succeed as a Real Estate Agent?",
    "status": "planned"
  },
  {
    "slug": "is-real-estate-a-good-career-change-for-teachers-in-volusia-county",
    "type": "article",
    "pillar": "decide",
    "title": "Is Real Estate a Good Career Change for Teachers in Volusia County?",
    "status": "planned"
  },
  {
    "slug": "is-real-estate-a-good-career-change-for-military-veterans-in-the-daytona-beach-a",
    "type": "article",
    "pillar": "decide",
    "title": "Is Real Estate a Good Career Change for Military Veterans in the Daytona Beach Area?",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-income-commission-splits-and-what-you-actually-take-home-in-fl",
    "type": "article",
    "pillar": "decide",
    "title": "Real Estate Agent Income: Commission, Splits, and What You Actually Take Home in Florida",
    "status": "planned"
  },
  {
    "slug": "the-truth-about-being-a-new-real-estate-agent-challenges-nobody-talks-about",
    "type": "article",
    "pillar": "decide",
    "title": "The Truth About Being a New Real Estate Agent: Challenges Nobody Talks About",
    "status": "planned"
  },
  {
    "slug": "how-long-does-it-take-to-close-your-first-deal-as-a-new-agent-in-volusia-county",
    "type": "article",
    "pillar": "decide",
    "title": "How Long Does It Take to Close Your First Deal as a New Agent in Volusia County?",
    "status": "planned"
  },
  {
    "slug": "real-estate-as-a-second-career-what-daytona-beach-professionals-should-know",
    "type": "article",
    "pillar": "decide",
    "title": "Real Estate as a Second Career: What Daytona Beach Professionals Should Know",
    "status": "planned"
  },
  {
    "slug": "can-retirees-build-a-successful-real-estate-career-in-palm-coast-or-ormond-beach",
    "type": "article",
    "pillar": "decide",
    "title": "Can Retirees Build a Successful Real Estate Career in Palm Coast or Ormond Beach?",
    "status": "planned"
  },
  {
    "slug": "what-personality-types-thrive-as-real-estate-agents-in-florida",
    "type": "article",
    "pillar": "decide",
    "title": "What Personality Types Thrive as Real Estate Agents in Florida?",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-vs-loan-officer-vs-property-manager-in-florida-which-path-fits",
    "type": "article",
    "pillar": "decide",
    "title": "Real Estate Agent vs. Loan Officer vs. Property Manager in Florida: Which Path Fits You?",
    "status": "planned"
  },
  {
    "slug": "how-the-daytona-beach-and-new-smyrna-beach-markets-affect-new-agent-earnings",
    "type": "article",
    "pillar": "decide",
    "title": "How the Daytona Beach and New Smyrna Beach Markets Affect New Agent Earnings",
    "status": "planned"
  },
  {
    "slug": "is-the-flagler-county-real-estate-market-big-enough-for-a-new-agent-to-thrive",
    "type": "article",
    "pillar": "decide",
    "title": "Is the Flagler County Real Estate Market Big Enough for a New Agent to Thrive?",
    "status": "planned"
  },
  {
    "slug": "myths-about-real-estate-careers-that-stop-people-from-getting-started",
    "type": "article",
    "pillar": "decide",
    "title": "Myths About Real Estate Careers That Stop People from Getting Started",
    "status": "planned"
  },
  {
    "slug": "how-to-know-if-youre-ready-to-leave-your-job-and-go-full-time-in-real-estate",
    "type": "article",
    "pillar": "decide",
    "title": "How to Know If You're Ready to Leave Your Job and Go Full-Time in Real Estate",
    "status": "planned"
  },
  {
    "slug": "choosing-a-real-estate-brokerage",
    "type": "hub",
    "pillar": "brokerage",
    "title": "Choose the Right Brokerage",
    "status": "planned"
  },
  {
    "slug": "how-to-choose-the-right-real-estate-brokerage-in-daytona-beach-as-a-new-agent",
    "type": "article",
    "pillar": "brokerage",
    "title": "How to Choose the Right Real Estate Brokerage in Daytona Beach as a New Agent",
    "status": "planned"
  },
  {
    "slug": "commission-splits-explained-what-new-agents-in-florida-should-negotiate",
    "type": "article",
    "pillar": "brokerage",
    "title": "Commission Splits Explained: What New Agents in Florida Should Negotiate",
    "status": "planned"
  },
  {
    "slug": "franchise-brokerages-vs-independent-brokerages-in-volusia-county-whats-the-diffe",
    "type": "article",
    "pillar": "brokerage",
    "title": "Franchise Brokerages vs. Independent Brokerages in Volusia County: What's the Difference?",
    "status": "planned"
  },
  {
    "slug": "flat-fee-brokerages-vs-traditional-splits-in-florida-which-is-better-for-new-age",
    "type": "article",
    "pillar": "brokerage",
    "title": "Flat-Fee Brokerages vs. Traditional Splits in Florida: Which Is Better for New Agents?",
    "status": "planned"
  },
  {
    "slug": "what-to-look-for-in-a-real-estate-brokerage-as-a-brand-new-florida-agent",
    "type": "article",
    "pillar": "brokerage",
    "title": "What to Look for in a Real Estate Brokerage as a Brand-New Florida Agent",
    "status": "planned"
  },
  {
    "slug": "questions-you-should-ask-every-brokerage-before-you-sign-in-volusia-county",
    "type": "article",
    "pillar": "brokerage",
    "title": "Questions You Should Ask Every Brokerage Before You Sign in Volusia County",
    "status": "planned"
  },
  {
    "slug": "what-does-broker-support-actually-look-like-at-daytona-beach-real-estate-offices",
    "type": "article",
    "pillar": "brokerage",
    "title": "What Does Broker Support Actually Look Like at Daytona Beach Real Estate Offices?",
    "status": "planned"
  },
  {
    "slug": "how-to-evaluate-a-brokerages-training-program-before-you-join",
    "type": "article",
    "pillar": "brokerage",
    "title": "How to Evaluate a Brokerage's Training Program Before You Join",
    "status": "planned"
  },
  {
    "slug": "real-estate-team-vs-solo-agent-which-path-is-right-in-the-daytona-beach-market",
    "type": "article",
    "pillar": "brokerage",
    "title": "Real Estate Team vs. Solo Agent: Which Path Is Right in the Daytona Beach Market?",
    "status": "planned"
  },
  {
    "slug": "do-big-name-brokerages-give-new-agents-in-flagler-county-an-advantage",
    "type": "article",
    "pillar": "brokerage",
    "title": "Do Big-Name Brokerages Give New Agents in Flagler County an Advantage?",
    "status": "planned"
  },
  {
    "slug": "how-brokerage-culture-affects-agent-success-in-volusia-county",
    "type": "article",
    "pillar": "brokerage",
    "title": "How Brokerage Culture Affects Agent Success in Volusia County",
    "status": "planned"
  },
  {
    "slug": "the-real-cost-of-joining-a-brokerage-in-florida-fees-dues-and-desk-costs",
    "type": "article",
    "pillar": "brokerage",
    "title": "The Real Cost of Joining a Brokerage in Florida: Fees, Dues, and Desk Costs",
    "status": "planned"
  },
  {
    "slug": "how-to-evaluate-a-brokerages-market-share-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "brokerage",
    "title": "How to Evaluate a Brokerage's Market Share in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "what-new-agents-in-deland-and-deltona-should-know-about-choosing-a-brokerage",
    "type": "article",
    "pillar": "brokerage",
    "title": "What New Agents in DeLand and Deltona Should Know About Choosing a Brokerage",
    "status": "planned"
  },
  {
    "slug": "100-commission-brokerages-in-florida-are-they-worth-it-for-new-agents",
    "type": "article",
    "pillar": "brokerage",
    "title": "100% Commission Brokerages in Florida: Are They Worth It for New Agents?",
    "status": "planned"
  },
  {
    "slug": "how-to-leave-a-brokerage-and-transfer-your-florida-real-estate-license",
    "type": "article",
    "pillar": "brokerage",
    "title": "How to Leave a Brokerage and Transfer Your Florida Real Estate License",
    "status": "planned"
  },
  {
    "slug": "signs-youve-outgrown-your-first-brokerage-in-volusia-county",
    "type": "article",
    "pillar": "brokerage",
    "title": "Signs You've Outgrown Your First Brokerage in Volusia County",
    "status": "planned"
  },
  {
    "slug": "what-experienced-agents-look-for-when-switching-brokerages-in-the-daytona-area",
    "type": "article",
    "pillar": "brokerage",
    "title": "What Experienced Agents Look for When Switching Brokerages in the Daytona Area",
    "status": "planned"
  },
  {
    "slug": "how-brokerage-technology-and-crm-tools-affect-your-business-in-2024",
    "type": "article",
    "pillar": "brokerage",
    "title": "How Brokerage Technology and CRM Tools Affect Your Business in 2024",
    "status": "planned"
  },
  {
    "slug": "does-your-brokerages-brand-matter-in-the-palm-coast-and-flagler-beach-market",
    "type": "article",
    "pillar": "brokerage",
    "title": "Does Your Brokerage's Brand Matter in the Palm Coast and Flagler Beach Market?",
    "status": "planned"
  },
  {
    "slug": "building-your-real-estate-business",
    "type": "hub",
    "pillar": "business",
    "title": "Build Your Business",
    "status": "planned"
  },
  {
    "slug": "how-to-build-a-real-estate-sphere-of-influence-in-daytona-beach-from-scratch",
    "type": "article",
    "pillar": "business",
    "title": "How to Build a Real Estate Sphere of Influence in Daytona Beach from Scratch",
    "status": "planned"
  },
  {
    "slug": "best-lead-generation-strategies-for-new-agents-in-volusia-county",
    "type": "article",
    "pillar": "business",
    "title": "Best Lead Generation Strategies for New Agents in Volusia County",
    "status": "planned"
  },
  {
    "slug": "how-to-farm-a-neighborhood-as-a-real-estate-agent-in-ormond-beach",
    "type": "article",
    "pillar": "business",
    "title": "How to Farm a Neighborhood as a Real Estate Agent in Ormond Beach",
    "status": "planned"
  },
  {
    "slug": "social-media-marketing-for-real-estate-agents-in-the-daytona-beach-market",
    "type": "article",
    "pillar": "business",
    "title": "Social Media Marketing for Real Estate Agents in the Daytona Beach Market",
    "status": "planned"
  },
  {
    "slug": "how-to-use-google-business-profile-to-get-real-estate-leads-in-flagler-county",
    "type": "article",
    "pillar": "business",
    "title": "How to Use Google Business Profile to Get Real Estate Leads in Flagler County",
    "status": "planned"
  },
  {
    "slug": "building-a-real-estate-brand-around-the-new-smyrna-beach-lifestyle",
    "type": "article",
    "pillar": "business",
    "title": "Building a Real Estate Brand Around the New Smyrna Beach Lifestyle",
    "status": "planned"
  },
  {
    "slug": "how-to-get-your-first-real-estate-listing-in-volusia-county",
    "type": "article",
    "pillar": "business",
    "title": "How to Get Your First Real Estate Listing in Volusia County",
    "status": "planned"
  },
  {
    "slug": "open-houses-that-actually-generate-leads-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "business",
    "title": "Open Houses That Actually Generate Leads in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "real-estate-referral-networks-how-to-build-one-in-the-palm-coast-market",
    "type": "article",
    "pillar": "business",
    "title": "Real Estate Referral Networks: How to Build One in the Palm Coast Market",
    "status": "planned"
  },
  {
    "slug": "email-marketing-for-real-estate-agents-in-volusia-and-flagler-county",
    "type": "article",
    "pillar": "business",
    "title": "Email Marketing for Real Estate Agents in Volusia and Flagler County",
    "status": "planned"
  },
  {
    "slug": "how-to-market-to-snowbirds-and-seasonal-buyers-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "business",
    "title": "How to Market to Snowbirds and Seasonal Buyers in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "building-a-niche-as-a-luxury-real-estate-agent-in-ormond-beach-or-ponte-vedra",
    "type": "article",
    "pillar": "business",
    "title": "Building a Niche as a Luxury Real Estate Agent in Ormond Beach or Ponte Vedra",
    "status": "planned"
  },
  {
    "slug": "how-to-market-to-first-time-homebuyers-in-deltona-and-deland",
    "type": "article",
    "pillar": "business",
    "title": "How to Market to First-Time Homebuyers in Deltona and DeLand",
    "status": "planned"
  },
  {
    "slug": "real-estate-video-marketing-for-agents-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "business",
    "title": "Real Estate Video Marketing for Agents in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "how-new-agents-in-flagler-county-can-compete-against-experienced-agents",
    "type": "article",
    "pillar": "business",
    "title": "How New Agents in Flagler County Can Compete Against Experienced Agents",
    "status": "planned"
  },
  {
    "slug": "the-best-crm-tools-for-real-estate-agents-working-the-volusia-county-market",
    "type": "article",
    "pillar": "business",
    "title": "The Best CRM Tools for Real Estate Agents Working the Volusia County Market",
    "status": "planned"
  },
  {
    "slug": "hosting-client-appreciation-events-in-the-daytona-beach-community",
    "type": "article",
    "pillar": "business",
    "title": "Hosting Client Appreciation Events in the Daytona Beach Community",
    "status": "planned"
  },
  {
    "slug": "how-to-build-a-real-estate-team-in-volusia-county",
    "type": "article",
    "pillar": "business",
    "title": "How to Build a Real Estate Team in Volusia County",
    "status": "planned"
  },
  {
    "slug": "networking-groups-and-organizations-for-real-estate-agents-in-daytona-beach",
    "type": "article",
    "pillar": "business",
    "title": "Networking Groups and Organizations for Real Estate Agents in Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "how-to-track-your-real-estate-business-kpis-in-your-first-year",
    "type": "article",
    "pillar": "business",
    "title": "How to Track Your Real Estate Business KPIs in Your First Year",
    "status": "planned"
  },
  {
    "slug": "volusia-flagler-real-estate-market",
    "type": "hub",
    "pillar": "market",
    "title": "Know the Local Market",
    "status": "planned"
  },
  {
    "slug": "volusia-county-real-estate-market-overview-for-new-agents",
    "type": "article",
    "pillar": "market",
    "title": "Volusia County Real Estate Market Overview for New Agents",
    "status": "planned"
  },
  {
    "slug": "flagler-county-real-estate-market-trends-agents-need-to-know",
    "type": "article",
    "pillar": "market",
    "title": "Flagler County Real Estate Market Trends Agents Need to Know",
    "status": "planned"
  },
  {
    "slug": "the-daytona-beach-real-estate-market-what-agents-should-know-in-2024",
    "type": "article",
    "pillar": "market",
    "title": "The Daytona Beach Real Estate Market: What Agents Should Know in 2024",
    "status": "planned"
  },
  {
    "slug": "why-palm-coast-is-one-of-floridas-fastest-growing-real-estate-markets",
    "type": "article",
    "pillar": "market",
    "title": "Why Palm Coast Is One of Florida's Fastest-Growing Real Estate Markets",
    "status": "planned"
  },
  {
    "slug": "new-smyrna-beach-real-estate-market-opportunities-for-local-agents",
    "type": "article",
    "pillar": "market",
    "title": "New Smyrna Beach Real Estate Market: Opportunities for Local Agents",
    "status": "planned"
  },
  {
    "slug": "ormond-beach-real-estate-a-neighborhood-by-neighborhood-guide-for-agents",
    "type": "article",
    "pillar": "market",
    "title": "Ormond Beach Real Estate: A Neighborhood-by-Neighborhood Guide for Agents",
    "status": "planned"
  },
  {
    "slug": "deland-real-estate-market-why-agents-are-paying-attention",
    "type": "article",
    "pillar": "market",
    "title": "DeLand Real Estate Market: Why Agents Are Paying Attention",
    "status": "planned"
  },
  {
    "slug": "deltona-real-estate-market-affordable-housing-and-what-it-means-for-agents",
    "type": "article",
    "pillar": "market",
    "title": "Deltona Real Estate Market: Affordable Housing and What It Means for Agents",
    "status": "planned"
  },
  {
    "slug": "flagler-beach-and-beverly-beach-niche-markets-worth-knowing-as-an-agent",
    "type": "article",
    "pillar": "market",
    "title": "Flagler Beach and Beverly Beach: Niche Markets Worth Knowing as an Agent",
    "status": "planned"
  },
  {
    "slug": "how-tourism-and-daytonas-events-calendar-affect-real-estate-sales-volume",
    "type": "article",
    "pillar": "market",
    "title": "How Tourism and Daytona's Events Calendar Affect Real Estate Sales Volume",
    "status": "planned"
  },
  {
    "slug": "seasonal-market-patterns-in-volusia-county-every-new-agent-should-understand",
    "type": "article",
    "pillar": "market",
    "title": "Seasonal Market Patterns in Volusia County Every New Agent Should Understand",
    "status": "planned"
  },
  {
    "slug": "waterfront-and-canal-properties-in-flagler-county-what-agents-need-to-know",
    "type": "article",
    "pillar": "market",
    "title": "Waterfront and Canal Properties in Flagler County: What Agents Need to Know",
    "status": "planned"
  },
  {
    "slug": "new-construction-communities-in-volusia-and-flagler-county-and-how-to-work-with-",
    "type": "article",
    "pillar": "market",
    "title": "New Construction Communities in Volusia and Flagler County and How to Work With Them",
    "status": "planned"
  },
  {
    "slug": "55-communities-in-the-daytona-beach-area-a-growing-niche-for-real-estate-agents",
    "type": "article",
    "pillar": "market",
    "title": "55+ Communities in the Daytona Beach Area: A Growing Niche for Real Estate Agents",
    "status": "planned"
  },
  {
    "slug": "short-term-rental-and-airbnb-real-estate-investing-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "market",
    "title": "Short-Term Rental and Airbnb Real Estate Investing in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "how-interstate-95-and-i-4-corridor-growth-affects-the-volusia-county-market",
    "type": "article",
    "pillar": "market",
    "title": "How Interstate 95 and I-4 Corridor Growth Affects the Volusia County Market",
    "status": "planned"
  },
  {
    "slug": "commercial-vs-residential-real-estate-opportunities-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "market",
    "title": "Commercial vs. Residential Real Estate Opportunities in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "understanding-hoa-communities-in-flagler-and-volusia-county-as-a-new-agent",
    "type": "article",
    "pillar": "market",
    "title": "Understanding HOA Communities in Flagler and Volusia County as a New Agent",
    "status": "planned"
  },
  {
    "slug": "how-cape-canaveral-and-space-coast-growth-spills-into-volusia-county-real-estate",
    "type": "article",
    "pillar": "market",
    "title": "How Cape Canaveral and Space Coast Growth Spills Into Volusia County Real Estate",
    "status": "planned"
  },
  {
    "slug": "comparing-daytona-beach-metro-real-estate-to-the-orlando-and-jacksonville-market",
    "type": "article",
    "pillar": "market",
    "title": "Comparing Daytona Beach Metro Real Estate to the Orlando and Jacksonville Markets",
    "status": "planned"
  },
  {
    "slug": "new-agent-training",
    "type": "hub",
    "pillar": "training",
    "title": "Training, Tools & Resources",
    "status": "planned"
  },
  {
    "slug": "what-training-should-you-expect-from-a-brokerage-as-a-new-florida-agent",
    "type": "article",
    "pillar": "training",
    "title": "What Training Should You Expect from a Brokerage as a New Florida Agent?",
    "status": "planned"
  },
  {
    "slug": "how-to-write-a-real-estate-purchase-contract-in-florida",
    "type": "article",
    "pillar": "training",
    "title": "How to Write a Real Estate Purchase Contract in Florida",
    "status": "planned"
  },
  {
    "slug": "florida-as-is-residential-contract-what-every-new-agent-must-know",
    "type": "article",
    "pillar": "training",
    "title": "Florida AS-IS Residential Contract: What Every New Agent Must Know",
    "status": "planned"
  },
  {
    "slug": "how-to-conduct-a-comparative-market-analysis-cma-in-volusia-county",
    "type": "article",
    "pillar": "training",
    "title": "How to Conduct a Comparative Market Analysis (CMA) in Volusia County",
    "status": "planned"
  },
  {
    "slug": "how-the-mls-works-in-volusia-and-flagler-county-for-new-agents",
    "type": "article",
    "pillar": "training",
    "title": "How the MLS Works in Volusia and Flagler County for New Agents",
    "status": "planned"
  },
  {
    "slug": "what-is-the-daytona-beach-area-association-of-realtors-and-should-you-join",
    "type": "article",
    "pillar": "training",
    "title": "What Is the Daytona Beach Area Association of Realtors and Should You Join?",
    "status": "planned"
  },
  {
    "slug": "nar-membership-and-dues-what-florida-agents-need-to-know",
    "type": "article",
    "pillar": "training",
    "title": "NAR Membership and Dues: What Florida Agents Need to Know",
    "status": "planned"
  },
  {
    "slug": "how-to-use-the-florida-realtors-forms-and-contracts-correctly",
    "type": "article",
    "pillar": "training",
    "title": "How to Use the Florida Realtors Forms and Contracts Correctly",
    "status": "planned"
  },
  {
    "slug": "what-e-and-o-insurance-is-and-why-every-florida-agent-needs-it",
    "type": "article",
    "pillar": "training",
    "title": "What E&O Insurance Is and Why Every Florida Agent Needs It",
    "status": "planned"
  },
  {
    "slug": "how-to-handle-your-first-buyer-consultation-as-a-new-agent-in-daytona-beach",
    "type": "article",
    "pillar": "training",
    "title": "How to Handle Your First Buyer Consultation as a New Agent in Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "how-to-host-an-open-house-professionally-in-volusia-county",
    "type": "article",
    "pillar": "training",
    "title": "How to Host an Open House Professionally in Volusia County",
    "status": "planned"
  },
  {
    "slug": "earnest-money-and-escrow-in-florida-a-new-agents-guide",
    "type": "article",
    "pillar": "training",
    "title": "Earnest Money and Escrow in Florida: A New Agent's Guide",
    "status": "planned"
  },
  {
    "slug": "florida-disclosure-requirements-what-sellers-must-tell-buyers",
    "type": "article",
    "pillar": "training",
    "title": "Florida Disclosure Requirements: What Sellers Must Tell Buyers",
    "status": "planned"
  },
  {
    "slug": "how-to-prepare-a-listing-presentation-that-wins-in-the-daytona-beach-market",
    "type": "article",
    "pillar": "training",
    "title": "How to Prepare a Listing Presentation That Wins in the Daytona Beach Market",
    "status": "planned"
  },
  {
    "slug": "what-happens-at-a-florida-real-estate-closing-and-whats-the-agents-role",
    "type": "article",
    "pillar": "training",
    "title": "What Happens at a Florida Real Estate Closing and What's the Agent's Role?",
    "status": "planned"
  },
  {
    "slug": "how-to-work-with-a-title-company-in-volusia-county",
    "type": "article",
    "pillar": "training",
    "title": "How to Work with a Title Company in Volusia County",
    "status": "planned"
  },
  {
    "slug": "understanding-the-florida-homestead-exemption-and-how-it-affects-your-clients",
    "type": "article",
    "pillar": "training",
    "title": "Understanding the Florida Homestead Exemption and How It Affects Your Clients",
    "status": "planned"
  },
  {
    "slug": "how-to-navigate-a-home-inspection-as-a-new-agent-in-flagler-county",
    "type": "article",
    "pillar": "training",
    "title": "How to Navigate a Home Inspection as a New Agent in Flagler County",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-safety-best-practices-for-showing-homes-in-volusia-county",
    "type": "article",
    "pillar": "training",
    "title": "Real Estate Agent Safety: Best Practices for Showing Homes in Volusia County",
    "status": "planned"
  },
  {
    "slug": "time-management-tips-for-new-real-estate-agents-in-a-competitive-florida-market",
    "type": "article",
    "pillar": "training",
    "title": "Time Management Tips for New Real Estate Agents in a Competitive Florida Market",
    "status": "planned"
  },
  {
    "slug": "how-to-handle-a-transaction-that-falls-apart-before-closing",
    "type": "article",
    "pillar": "training",
    "title": "How to Handle a Transaction That Falls Apart Before Closing",
    "status": "planned"
  },
  {
    "slug": "tax-deductions-every-self-employed-real-estate-agent-in-florida-should-know",
    "type": "article",
    "pillar": "training",
    "title": "Tax Deductions Every Self-Employed Real Estate Agent in Florida Should Know",
    "status": "planned"
  },
  {
    "slug": "real-estate-license-upgrades",
    "type": "hub",
    "pillar": "advancement",
    "title": "Advance & Upgrade Your License",
    "status": "planned"
  },
  {
    "slug": "how-to-get-your-florida-real-estate-broker-license",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Get Your Florida Real Estate Broker License",
    "status": "planned"
  },
  {
    "slug": "florida-broker-associate-license-is-it-worth-it-for-experienced-agents",
    "type": "article",
    "pillar": "advancement",
    "title": "Florida Broker Associate License: Is It Worth It for Experienced Agents?",
    "status": "planned"
  },
  {
    "slug": "when-should-you-upgrade-from-sales-associate-to-broker-in-florida",
    "type": "article",
    "pillar": "advancement",
    "title": "When Should You Upgrade from Sales Associate to Broker in Florida?",
    "status": "planned"
  },
  {
    "slug": "florida-broker-license-requirements-experience-education-and-exam",
    "type": "article",
    "pillar": "advancement",
    "title": "Florida Broker License Requirements: Experience, Education, and Exam",
    "status": "planned"
  },
  {
    "slug": "how-to-open-your-own-real-estate-brokerage-in-volusia-county",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Open Your Own Real Estate Brokerage in Volusia County",
    "status": "planned"
  },
  {
    "slug": "real-estate-designations-worth-earning-in-florida-abr-crs-gri-and-more",
    "type": "article",
    "pillar": "advancement",
    "title": "Real Estate Designations Worth Earning in Florida: ABR, CRS, GRI, and More",
    "status": "planned"
  },
  {
    "slug": "how-the-gri-designation-helps-agents-in-the-daytona-beach-market",
    "type": "article",
    "pillar": "advancement",
    "title": "How the GRI Designation Helps Agents in the Daytona Beach Market",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-continuing-education-what-courses-you-actually-need",
    "type": "article",
    "pillar": "advancement",
    "title": "Florida Real Estate Continuing Education: What Courses You Actually Need",
    "status": "planned"
  },
  {
    "slug": "how-to-become-a-real-estate-team-leader-in-volusia-county",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Become a Real Estate Team Leader in Volusia County",
    "status": "planned"
  },
  {
    "slug": "from-solo-agent-to-team-hiring-your-first-assistant-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "advancement",
    "title": "From Solo Agent to Team: Hiring Your First Assistant in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "how-to-add-property-management-to-your-real-estate-business-in-flagler-county",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Add Property Management to Your Real Estate Business in Flagler County",
    "status": "planned"
  },
  {
    "slug": "commercial-real-estate-certifications-for-agents-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "advancement",
    "title": "Commercial Real Estate Certifications for Agents in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "how-to-build-a-referral-based-business-after-five-years-in-volusia-county-real-e",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Build a Referral-Based Business After Five Years in Volusia County Real Estate",
    "status": "planned"
  },
  {
    "slug": "mentorship-programs-for-real-estate-agents-in-the-daytona-beach-area",
    "type": "article",
    "pillar": "advancement",
    "title": "Mentorship Programs for Real Estate Agents in the Daytona Beach Area",
    "status": "planned"
  },
  {
    "slug": "how-to-transition-from-residential-to-luxury-real-estate-in-ormond-beach",
    "type": "article",
    "pillar": "advancement",
    "title": "How to Transition from Residential to Luxury Real Estate in Ormond Beach",
    "status": "planned"
  },
  {
    "slug": "building-passive-income-as-a-florida-real-estate-agent",
    "type": "article",
    "pillar": "advancement",
    "title": "Building Passive Income as a Florida Real Estate Agent",
    "status": "planned"
  },
  {
    "slug": "how-real-estate-coaching-programs-help-agents-in-volusia-county-scale-faster",
    "type": "article",
    "pillar": "advancement",
    "title": "How Real Estate Coaching Programs Help Agents in Volusia County Scale Faster",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-income-florida",
    "type": "hub",
    "pillar": "income",
    "title": "Income, Costs & Tools",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-startup-cost-calculator-for-florida",
    "type": "article",
    "pillar": "income",
    "title": "Real Estate Agent Startup Cost Calculator for Florida",
    "status": "planned"
  },
  {
    "slug": "commission-split-calculator-how-much-will-you-earn-at-different-brokerages",
    "type": "article",
    "pillar": "income",
    "title": "Commission Split Calculator: How Much Will You Earn at Different Brokerages?",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-agent-income-estimator-by-production-level",
    "type": "article",
    "pillar": "income",
    "title": "Florida Real Estate Agent Income Estimator by Production Level",
    "status": "planned"
  },
  {
    "slug": "how-much-does-it-cost-to-maintain-a-florida-real-estate-license-each-year",
    "type": "article",
    "pillar": "income",
    "title": "How Much Does It Cost to Maintain a Florida Real Estate License Each Year?",
    "status": "planned"
  },
  {
    "slug": "first-year-real-estate-agent-budget-template-for-volusia-county",
    "type": "article",
    "pillar": "income",
    "title": "First-Year Real Estate Agent Budget Template for Volusia County",
    "status": "planned"
  },
  {
    "slug": "how-many-transactions-do-you-need-to-make-50000-in-volusia-county-real-estate",
    "type": "article",
    "pillar": "income",
    "title": "How Many Transactions Do You Need to Make $50,000 in Volusia County Real Estate?",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-tax-planning-worksheet-for-florida-independent-contractors",
    "type": "article",
    "pillar": "income",
    "title": "Real Estate Agent Tax Planning Worksheet for Florida Independent Contractors",
    "status": "planned"
  },
  {
    "slug": "marketing-budget-calculator-for-new-real-estate-agents-in-daytona-beach",
    "type": "article",
    "pillar": "income",
    "title": "Marketing Budget Calculator for New Real Estate Agents in Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "break-even-calculator-when-will-your-real-estate-business-become-profitable",
    "type": "article",
    "pillar": "income",
    "title": "Break-Even Calculator: When Will Your Real Estate Business Become Profitable?",
    "status": "planned"
  },
  {
    "slug": "comparing-brokerage-fee-structures-side-by-side-cost-analysis-tool",
    "type": "article",
    "pillar": "income",
    "title": "Comparing Brokerage Fee Structures: Side-by-Side Cost Analysis Tool",
    "status": "planned"
  },
  {
    "slug": "how-to-set-a-realistic-income-goal-for-your-first-year-in-real-estate",
    "type": "article",
    "pillar": "income",
    "title": "How to Set a Realistic Income Goal for Your First Year in Real Estate",
    "status": "planned"
  },
  {
    "slug": "the-hidden-costs-new-agents-dont-expect-when-starting-in-florida",
    "type": "article",
    "pillar": "income",
    "title": "The Hidden Costs New Agents Don't Expect When Starting in Florida",
    "status": "planned"
  },
  {
    "slug": "what-does-it-actually-cost-to-get-your-florida-real-estate-license-start-to-fini",
    "type": "article",
    "pillar": "income",
    "title": "What Does It Actually Cost to Get Your Florida Real Estate License Start to Finish?",
    "status": "planned"
  },
  {
    "slug": "how-commission-works-in-a-buyers-agent-vs-listing-agent-transaction-in-florida",
    "type": "article",
    "pillar": "income",
    "title": "How Commission Works in a Buyer's Agent vs. Listing Agent Transaction in Florida",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-stories-daytona",
    "type": "hub",
    "pillar": "stories",
    "title": "Stories, Culture & Community",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-success-stories-from-daytona-beach-and-volusia-county",
    "type": "article",
    "pillar": "stories",
    "title": "Real Estate Agent Success Stories from Daytona Beach and Volusia County",
    "status": "planned"
  },
  {
    "slug": "from-hospitality-worker-to-real-estate-agent-in-daytona-beach-real-career-pivots",
    "type": "article",
    "pillar": "stories",
    "title": "From Hospitality Worker to Real Estate Agent in Daytona Beach: Real Career Pivots",
    "status": "planned"
  },
  {
    "slug": "how-a-former-educator-built-a-top-real-estate-career-in-flagler-county",
    "type": "article",
    "pillar": "stories",
    "title": "How a Former Educator Built a Top Real Estate Career in Flagler County",
    "status": "planned"
  },
  {
    "slug": "meet-the-agents-who-is-thriving-in-the-palm-coast-real-estate-market",
    "type": "article",
    "pillar": "stories",
    "title": "Meet the Agents: Who Is Thriving in the Palm Coast Real Estate Market?",
    "status": "planned"
  },
  {
    "slug": "what-the-daytona-500-and-bike-week-teach-real-estate-agents-about-the-local-econ",
    "type": "article",
    "pillar": "stories",
    "title": "What the Daytona 500 and Bike Week Teach Real Estate Agents About the Local Economy",
    "status": "planned"
  },
  {
    "slug": "why-agents-choose-to-build-their-career-in-new-smyrna-beach-vs-daytona-beach",
    "type": "article",
    "pillar": "stories",
    "title": "Why Agents Choose to Build Their Career in New Smyrna Beach vs. Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "community-involvement-and-real-estate-success-in-ormond-beach",
    "type": "article",
    "pillar": "stories",
    "title": "Community Involvement and Real Estate Success in Ormond Beach",
    "status": "planned"
  },
  {
    "slug": "how-local-market-knowledge-gives-volusia-county-agents-a-competitive-edge",
    "type": "article",
    "pillar": "stories",
    "title": "How Local Market Knowledge Gives Volusia County Agents a Competitive Edge",
    "status": "planned"
  },
  {
    "slug": "why-flagler-county-is-attracting-new-real-estate-agents-from-across-florida",
    "type": "article",
    "pillar": "stories",
    "title": "Why Flagler County Is Attracting New Real Estate Agents from Across Florida",
    "status": "planned"
  },
  {
    "slug": "the-role-of-the-daytona-beach-area-association-of-realtors-in-agent-careers",
    "type": "article",
    "pillar": "stories",
    "title": "The Role of the Daytona Beach Area Association of Realtors in Agent Careers",
    "status": "planned"
  },
  {
    "slug": "women-in-real-estate-building-careers-in-volusia-and-flagler-county",
    "type": "article",
    "pillar": "stories",
    "title": "Women in Real Estate: Building Careers in Volusia and Flagler County",
    "status": "planned"
  },
  {
    "slug": "second-career-success-stories-agents-who-started-late-and-thrived-in-daytona-bea",
    "type": "article",
    "pillar": "stories",
    "title": "Second-Career Success Stories: Agents Who Started Late and Thrived in Daytona Beach",
    "status": "planned"
  },
  {
    "slug": "how-military-families-relocating-to-the-daytona-beach-area-create-opportunity-fo",
    "type": "article",
    "pillar": "stories",
    "title": "How Military Families Relocating to the Daytona Beach Area Create Opportunity for Agents",
    "status": "planned"
  },
  {
    "slug": "real-estate-agent-life-in-deland-small-town-feel-real-market-opportunity",
    "type": "article",
    "pillar": "stories",
    "title": "Real Estate Agent Life in DeLand: Small Town Feel, Real Market Opportunity",
    "status": "planned"
  },
  {
    "slug": "why-deltonas-growth-is-creating-new-career-opportunities-for-real-estate-agents",
    "type": "article",
    "pillar": "stories",
    "title": "Why Deltona's Growth Is Creating New Career Opportunities for Real Estate Agents",
    "status": "planned"
  },
  {
    "slug": "florida-real-estate-license-guide",
    "type": "article",
    "pillar": "license",
    "title": "florida-real-estate-license-guide",
    "status": "built",
    "spec": "content/florida-real-estate-license-guide.json"
  },
  {
    "slug": "become-a-real-estate-agent-daytona-beach",
    "type": "article",
    "pillar": "local",
    "title": "become-a-real-estate-agent-daytona-beach",
    "status": "built",
    "spec": "content/become-a-real-estate-agent-daytona-beach.json"
  }
],
};
